version: '3.8'

services:
  app:
    build: .
    container_name: calendar-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - app-data:/app/data
    environment:
      - OPENWEATHER_API_KEY=redacted
      - SECRET_KEY=redacted
    depends_on:
      - db
    restart: unless-stopped
    command: >
      bash -c "uvicorn calendarProject:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: keinos/sqlite3:latest
    container_name: calendar-db
    volumes:
      - app-data:/data
    restart: unless-stopped

volumes:
  app-data:
